### ISSUE TITLE
Bad Request Error on running the script.

### ISSUE THREAD

**Issue by Manan-31** [moh53n/FitBridge#5]
Hello, Sorry to raise an issue again, even though you gave up the device, I was hoping you might help me out with the following error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/FitBridge", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/FitBridge/main.py", line 287, in main
    credentials = auth(conf_dir)
                  ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/FitBridge/main.py", line 132, in auth
    credentials.refresh(Request())
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/google/oauth2/credentials.py", line 430, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/google/oauth2/reauth.py", line 365, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/google/oauth2/_client.py", line 72, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})

It shows up when running FitBridge command. I uninstalled and reinstalled the module but after reinstalling, instead of the initial setup, it shows the above error again.

Thank you for your help.

**Comment by moh53n** [comment]
Must be fixed now. Please update with `pip install FitBridge --upgrade` and report back.
